const alfozPlaces = [
    { name: 'Alcedo', path: '/lugares/alfozcerezolantaron/Alcedo/index.html', description: 'Descubre más sobre Alcedo.' },
    { name: 'Ameyugo', path: '/lugares/alfozcerezolantaron/Ameyugo/index.html', description: 'Descubre más sobre Ameyugo.' },
    { name: 'Bachicabo', path: '/lugares/alfozcerezolantaron/Bachicabo/index.html', description: 'Descubre más sobre Bachicabo.' },
    { name: 'Barrio', path: '/lugares/alfozcerezolantaron/Barrio/index.html', description: 'Descubre más sobre Barrio.' },
    { name: 'Belorado', path: '/lugares/alfozcerezolantaron/Belorado/index.html', description: 'Descubre más sobre Belorado.' },
    { name: 'Berguenda', path: '/lugares/alfozcerezolantaron/Berguenda/index.html', description: 'Descubre más sobre Berguenda.' },
    { name: 'Caicedo de Yuso', path: '/lugares/alfozcerezolantaron/Caicedo_de_Yuso/index.html', description: 'Descubre más sobre Caicedo de Yuso.' },
    { name: 'Carcamo', path: '/lugares/alfozcerezolantaron/Carcamo/index.html', description: 'Descubre más sobre Carcamo.' },
    { name: 'Castellum', path: '/lugares/alfozcerezolantaron/Castellum/index.html', description: 'Descubre más sobre Castellum.' },
    { name: 'Cellorigo', path: '/lugares/alfozcerezolantaron/Cellorigo/index.html', description: 'Descubre más sobre Cellorigo.' },
    { name: 'Cerezo de Rio Tiron', path: '/lugares/alfozcerezolantaron/Cerezo_de_Rio_Tiron/index.html', description: 'Descubre más sobre Cerezo de Rio Tiron.' },
    { name: 'Comunion', path: '/lugares/alfozcerezolantaron/Comunion/index.html', description: 'Descubre más sobre Comunion.' },
    { name: 'Cuzcurrita de Rio Tiron', path: '/lugares/alfozcerezolantaron/Cuzcurrita_de_Rio_Tiron/index.html', description: 'Descubre más sobre Cuzcurrita de Rio Tiron.' },
    { name: 'Espejo', path: '/lugares/alfozcerezolantaron/Espejo/index.html', description: 'Descubre más sobre Espejo.' },
    { name: 'Fontecha', path: '/lugares/alfozcerezolantaron/Fontecha/index.html', description: 'Descubre más sobre Fontecha.' },
    { name: 'Fresno de Rio Tiron', path: '/lugares/alfozcerezolantaron/Fresno_de_Rio_Tiron/index.html', description: 'Descubre más sobre Fresno de Rio Tiron.' },
    { name: 'Granon', path: '/lugares/alfozcerezolantaron/Granon/index.html', description: 'Descubre más sobre Granon.' },
    { name: 'Gurendes', path: '/lugares/alfozcerezolantaron/Gurendes/index.html', description: 'Descubre más sobre Gurendes.' },
    { name: 'Herramelluri', path: '/lugares/alfozcerezolantaron/Herramelluri/index.html', description: 'Descubre más sobre Herramelluri.' },
    { name: 'Ibrillos', path: '/lugares/alfozcerezolantaron/Ibrillos/index.html', description: 'Descubre más sobre Ibrillos.' },
    { name: 'Lecinana del Camino', path: '/lugares/alfozcerezolantaron/Lecinana_del_Camino/index.html', description: 'Descubre más sobre Lecinana del Camino.' },
    { name: 'Molinilla', path: '/lugares/alfozcerezolantaron/Molinilla/index.html', description: 'Descubre más sobre Molinilla.' },
    { name: 'Monte', path: '/lugares/alfozcerezolantaron/Monte/index.html', description: 'Descubre más sobre Monte.' },
    { name: 'Nograro', path: '/lugares/alfozcerezolantaron/Nograro/index.html', description: 'Descubre más sobre Nograro.' },
    { name: 'Ochanduri', path: '/lugares/alfozcerezolantaron/Ochanduri/index.html', description: 'Descubre más sobre Ochanduri.' },
    { name: 'Pancorbo', path: '/lugares/alfozcerezolantaron/Pancorbo/index.html', description: 'Descubre más sobre Pancorbo.' },
    { name: 'Pinedo', path: '/lugares/alfozcerezolantaron/Pinedo/index.html', description: 'Descubre más sobre Pinedo.' },
    { name: 'Posada', path: '/lugares/alfozcerezolantaron/Posada/index.html', description: 'Descubre más sobre Posada.' },
    { name: 'Poza de la Sal', path: '/lugares/alfozcerezolantaron/Poza_de_la_Sal/index.html', description: 'Descubre más sobre Poza de la Sal.' },
    { name: 'Puentelarra', path: '/lugares/alfozcerezolantaron/Puentelarra/index.html', description: 'Descubre más sobre Puentelarra.' },
    { name: 'Quejo', path: '/lugares/alfozcerezolantaron/Quejo/index.html', description: 'Descubre más sobre Quejo.' },
    { name: 'Quintanaloranco', path: '/lugares/alfozcerezolantaron/Quintanaloranco/index.html', description: 'Descubre más sobre Quintanaloranco.' },
    { name: 'Quintanilla del Monte', path: '/lugares/alfozcerezolantaron/Quintanilla_del_Monte/index.html', description: 'Descubre más sobre Quintanilla del Monte.' },
    { name: 'Quintanilla San Garcia', path: '/lugares/alfozcerezolantaron/Quintanilla_San_Garcia/index.html', description: 'Descubre más sobre Quintanilla San Garcia.' },
    { name: 'Recilla', path: '/lugares/alfozcerezolantaron/Recilla/index.html', description: 'Descubre más sobre Recilla.' },
    { name: 'Redecilla del Campo', path: '/lugares/alfozcerezolantaron/Redecilla_del_Campo/index.html', description: 'Descubre más sobre Redecilla del Campo.' },
    { name: 'Salcedo', path: '/lugares/alfozcerezolantaron/Salcedo/index.html', description: 'Descubre más sobre Salcedo.' },
    { name: 'San Emilianus', path: '/lugares/alfozcerezolantaron/San_Emilianus/index.html', description: 'Descubre más sobre San Emilianus.' },
    { name: 'San Millan de Yecora', path: '/lugares/alfozcerezolantaron/San_Millan_de_Yecora/index.html', description: 'Descubre más sobre San Millan de Yecora.' },
    { name: 'San Zadornil', path: '/lugares/alfozcerezolantaron/San_Zadornil/index.html', description: 'Descubre más sobre San Zadornil.' },
    { name: 'Sobron', path: '/lugares/alfozcerezolantaron/Sobron/index.html', description: 'Descubre más sobre Sobron.' },
    { name: 'Sotillo de Rioja', path: '/lugares/alfozcerezolantaron/Sotillo_de_Rioja/index.html', description: 'Descubre más sobre Sotillo de Rioja.' },
    { name: 'Tirgo', path: '/lugares/alfozcerezolantaron/Tirgo/index.html', description: 'Descubre más sobre Tirgo.' },
    { name: 'Tormantos', path: '/lugares/alfozcerezolantaron/Tormantos/index.html', description: 'Descubre más sobre Tormantos.' },
    { name: 'Trevino', path: '/lugares/alfozcerezolantaron/Trevino/index.html', description: 'Descubre más sobre Trevino.' },
    { name: 'Tuesta', path: '/lugares/alfozcerezolantaron/Tuesta/index.html', description: 'Descubre más sobre Tuesta.' },
    { name: 'Turiso', path: '/lugares/alfozcerezolantaron/Turiso/index.html', description: 'Descubre más sobre Turiso.' },
    { name: 'Valluercanes', path: '/lugares/alfozcerezolantaron/Valluercanes/index.html', description: 'Descubre más sobre Valluercanes.' },
    { name: 'Valpuesta', path: '/lugares/alfozcerezolantaron/Valpuesta/index.html', description: 'Descubre más sobre Valpuesta.' },
    { name: 'Velasco', path: '/lugares/alfozcerezolantaron/Velasco/index.html', description: 'Descubre más sobre Velasco.' },
    { name: 'Vilanespera', path: '/lugares/alfozcerezolantaron/Vilanespera/index.html', description: 'Descubre más sobre Vilanespera.' },
    { name: 'Villabezana', path: '/lugares/alfozcerezolantaron/Villabezana/index.html', description: 'Descubre más sobre Villabezana.' },
    { name: 'Villacanes', path: '/lugares/alfozcerezolantaron/Villacanes/index.html', description: 'Descubre más sobre Villacanes.' },
    { name: 'Villafria de San Zadornil', path: '/lugares/alfozcerezolantaron/Villafria_de_San_Zadornil/index.html', description: 'Descubre más sobre Villafria de San Zadornil.' },
    { name: 'Villalba de Losa', path: '/lugares/alfozcerezolantaron/Villalba_de_Losa/index.html', description: 'Descubre más sobre Villalba de Losa.' },
    { name: 'Villalmanzo', path: '/lugares/alfozcerezolantaron/Villalmanzo/index.html', description: 'Descubre más sobre Villalmanzo.' },
    { name: 'Villalomez', path: '/lugares/alfozcerezolantaron/Villalomez/index.html', description: 'Descubre más sobre Villalomez.' },
    { name: 'Villamaderne', path: '/lugares/alfozcerezolantaron/Villamaderne/index.html', description: 'Descubre más sobre Villamaderne.' },
    { name: 'Villanueva del Condado', path: '/lugares/alfozcerezolantaron/Villanueva_del_Condado/index.html', description: 'Descubre más sobre Villanueva del Condado.' },
    { name: 'Villanueva de Teba', path: '/lugares/alfozcerezolantaron/Villanueva_de_Teba/index.html', description: 'Descubre más sobre Villanueva de Teba.' },
    { name: 'Villapanillo', path: '/lugares/alfozcerezolantaron/Villapanillo/index.html', description: 'Descubre más sobre Villapanillo.' },
    { name: 'Villarea', path: '/lugares/alfozcerezolantaron/Villarea/index.html', description: 'Descubre más sobre Villarea.' },
    { name: 'Villarta Quintana', path: '/lugares/alfozcerezolantaron/Villarta_Quintana/index.html', description: 'Descubre más sobre Villarta Quintana.' },
    { name: 'Villatomil', path: '/lugares/alfozcerezolantaron/Villatomil/index.html', description: 'Descubre más sobre Villatomil.' },
    { name: 'Villatomil Astorga', path: '/lugares/alfozcerezolantaron/Villatomil_Astorga/index.html', description: 'Descubre más sobre Villatomil Astorga.' },
    { name: 'Villespin', path: '/lugares/alfozcerezolantaron/Villespin/index.html', description: 'Descubre más sobre Villespin.' },
    { name: 'Viloria de Rioja', path: '/lugares/alfozcerezolantaron/Viloria_de_Rioja/index.html', description: 'Descubre más sobre Viloria de Rioja.' },
    { name: 'Zabal', path: '/lugares/alfozcerezolantaron/Zabal/index.html', description: 'Descubre más sobre Zabal.' }
];
