version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app/frontend
    command: ["pnpm", "run", "dev", "--host", "0.0.0.0"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    command: ["python", "flask_app.py"]
