<?php require_once __DIR__ . '/../includes/head_common.php'; ?>
<head>
    <title>Capítulo 10: Cerezo en la Edad Moderna (Siglos XVI-XVIII): Entre la Tradición y las Nuevas Corrientes</title>
</head>
<body>
    <?php require_once __DIR__ . '/../_header_template.php'; ?>
    <h1>Capítulo 10: Cerezo en la Edad Moderna (Siglos XVI-XVIII): Entre la Tradición y las Nuevas Corrientes</h1>

    <section id="introduccion-antiguo-regimen">
        <h2>Introducción: Cerezo en el Antiguo Régimen</h2>
        <p>Con el advenimiento de la Edad Moderna, un periodo que en la historia de España se suele enmarcar con el reinado de los Reyes Católicos y la consolidación de la Monarquía Hispánica, Cerezo de Río Tirón, al igual que el conjunto de Castilla, se adentra en la compleja etapa conocida como el Antiguo Régimen. Esta era, que abarca los siglos XVI, XVII y XVIII, se caracterizará por la notable pervivencia de estructuras sociales, económicas y mentales heredadas del medievo, pero también por la paulatina irrupción de nuevas corrientes políticas, transformaciones culturales y profundas crisis religiosas que irán modelando, de forma lenta pero inexorable, la fisonomía de la villa y la vida cotidiana de sus habitantes.</p>
        <p>Este capítulo se propone explorar cómo Cerezo de Río Tirón navegó estos siglos de profundos contrastes: desde el aparente esplendor imperial de los Austrias Mayores y sus complejas repercusiones a escala local, pasando por las severas crisis del siglo XVII, hasta las reformas racionalizadoras y el incipiente centralismo impulsado por los primeros monarcas de la dinastía borbónica. Analizaremos, dentro de lo que las fuentes y la extrapolación histórica plausible nos permitan, la administración y el gobierno local, la persistente economía eminentemente agraria, la rígida sociedad estamental que definía el lugar de cada individuo, y la profunda e omnipresente influencia de la vida religiosa en una época marcada por la afirmación de la identidad católica post-tridentina. Aunque Cerezo quizás no fuera protagonista directo de los grandes acontecimientos de la política cortesana o de los vastos imperios ultramarinos, su microcosmos reflejaría, sin duda, las tensiones, continuidades y transformaciones de la España moderna, partiendo de la situación descrita en el <a href='capitulo9.php#conclusion-umbral-modernidad'>capítulo anterior sobre el umbral de la Modernidad</a>.</p>
    </section>

    <section id="administracion-gobierno-local">
        <h2>Administración y Gobierno Local Bajo los Austrias y Borbones</h2>
        <p>Durante la Edad Moderna, el gobierno local de Cerezo continuaría articulándose fundamentalmente en torno al concejo, institución heredera de las robustas tradiciones municipales forjadas en la Edad Media. Este concejo estaría compuesto por los vecinos más prominentes de la villa, aquellos que ostentaban la calidad de "vecinos con casa poblada y hacienda", generalmente pertenecientes a la oligarquía local de hidalgos y propietarios rurales acomodados. Sus competencias abarcarían la gestión de los vitales bienes comunales (montes, pastos, dehesas), el abasto de productos básicos a la villa, la regulación de los mercados y ferias, la administración de justicia en primera instancia para delitos menores y pleitos civiles, y la recaudación de una parte de los impuestos reales y municipales. No obstante, es crucial señalar que la autonomía municipal, tan celosamente defendida en siglos anteriores, se vería progresivamente limitada por el creciente poder y la intervención de la monarquía, especialmente a través de la figura del corregidor, un oficial real con amplias atribuciones que supervisaba y controlaba la vida de los municipios más importantes de su partido o corregimiento.</p>
        <p>Bajo la dinastía de los Austrias (siglos XVI y XVII), una práctica que se generalizó, impulsada por las acuciantes necesidades financieras de una Corona embarcada en costosas empresas europeas, fue la venta de oficios concejiles (regidurías perpetuas, escribanías, alguacilazgos). Este fenómeno pudo llevar, también en Cerezo, a la patrimonialización de los cargos públicos y a la consolidación de ciertas élites locales en el poder municipal, dificultando la renovación y la participación de otros sectores sociales. La villa de Cerezo, por su trayectoria histórica y su posible condición de cabeza de comarca o señorío (si lo tuvo en algún momento de este periodo), contaría con un cuerpo de regidores, alcaldes ordinarios (encargados de la justicia local en primera instancia) y un escribano público que daría fe de los acuerdos concejiles, las transacciones económicas y los testamentos.</p>
        <p>Con la llegada de la dinastía borbónica al trono español a principios del siglo XVIII, se acentuó la política centralizadora y de racionalización administrativa, inspirada en el modelo francés. Nuevas figuras, como el intendente provincial, buscarían una gestión más eficiente de los recursos, una mejora en la recaudación fiscal y una mayor uniformidad en la administración territorial. Es plausible que Cerezo, como otras muchas villas castellanas, experimentara reformas en su gobierno municipal y en su régimen fiscal, buscando una mayor eficiencia y sumisión a los dictados del poder central, pero siempre dentro del marco de una monarquía absoluta que veía en los municipios una pieza más, aunque importante, de su complejo engranaje estatal. La tensión dialéctica entre las arraigadas tradiciones locales de autogobierno y las crecientes imposiciones del poder central sería, pues, una constante a lo largo de estos siglos.</p>
    </section>

    <section id="economia-agraria-ganadera">
        <h2>Economía Agraria y Ganadera: Continuidades y Tímidos Cambios</h2>
        <p>La estructura económica de Cerezo en la Edad Moderna seguiría pivotando sobre una base eminentemente agraria y ganadera, perpetuando en gran medida los patrones productivos heredados de la Edad Media. Los cultivos predominantes en su término y alfoz serían los tradicionales cereales de secano (trigo y cebada, fundamentalmente), la vid —cuyo producto, el vino, era esencial tanto para el consumo local como para el comercio comarcal— y, en menor medida y en las zonas más propicias, el olivo. Los huertos familiares, situados en las inmediaciones de la villa o de las aldeas, proveerían de hortalizas, legumbres y frutas indispensables para el autoconsumo y la diversificación de la dieta. En el ámbito ganadero, la cría de ganado ovino, crucial por su lana (materia prima de la importante industria textil castellana y producto de exportación), y la de ganado bovino, indispensable para las labores de tiro en el campo y para el suministro de carne, mantendrían su secular importancia. La Mesta, la poderosa asociación de ganaderos trashumantes, seguiría regulando los flujos ganaderos a través de la Península, y sus cañadas reales y cordeles atravesarían o bordearían el término de Cerezo, generando no sin frecuencia posibles conflictos de intereses con los agricultores locales por el uso de los pastos y las rutas.</p>
        <p>No obstante esta fuerte continuidad, se introducirían algunos cambios, aunque de forma lenta y gradual. La llegada a Europa de nuevos cultivos procedentes de América, como el maíz o la patata, comenzaría a transformar paulatinamente la agricultura del continente a partir del siglo XVI. Su adopción en la Castilla interior, sin embargo, pudo ser más tardía y su difusión más lenta que en otras regiones periféricas o con mejores condiciones de irrigación. Es posible que no fuera hasta bien entrados los siglos XVII o incluso XVIII cuando estos nuevos productos empezaran a tener una presencia significativa en los campos de Cerezo, diversificando la producción agrícola y ofreciendo valiosas alternativas alimentarias, especialmente en épocas de malas cosechas de cereal, tan frecuentes en la agricultura de secano.</p>
        <p>En cuanto al régimen de propiedad de la tierra, este seguiría caracterizado por la compleja coexistencia de pequeñas y medianas propiedades campesinas (tanto alodios como tierras bajo diversos tipos de censo o arrendamiento), grandes extensiones en manos de la nobleza local o foránea y, muy especialmente, de la Iglesia (parroquias, cabildos, monasterios y conventos, que a menudo explotaban sus dominios mediante contratos de arrendamiento o aparcería), junto con los importantes bienes de propios y comunales, fundamentales para la economía de las familias más modestas. Las crisis de subsistencia, desencadenadas por sequías pertinaces, plagas (como la langosta) o cosechas catastróficas, seguirían siendo una amenaza recurrente, golpeando con dureza a las familias campesinas, disparando los precios de los alimentos y generando profundas tensiones sociales y demográficas.</p>
    </section>

    <section id="sociedad-estamental">
        <h2>Sociedad Estamental Cerezana: Privilegio, Riqueza y Trabajo</h2>
        <p>La sociedad de Cerezo, fiel reflejo de la estructura social de la España del Antiguo Régimen, era profundamente estamental y jerárquica, dividida fundamentalmente en dos grandes grupos: los privilegiados (nobleza y clero) y los no privilegiados (el estado llano o "pecheros"). En la cúspide de la pirámide social local se encontrarían las familias hidalgas, pertenecientes a la nobleza de segunda categoría, exentas del pago de la mayoría de los impuestos directos (los "pechos") y que basaban su prestigio y preeminencia social en la posesión de tierras (aunque no siempre extensas), en el recuerdo de servicios militares prestados por sus antepasados o en el desempeño de los principales cargos y oficios del concejo. Estos hidalgos, a menudo imbuidos de un fuerte sentido del honor y celosos defensores de sus prerrogativas, ejercerían una notable influencia en todos los aspectos de la vida de la villa.</p>
        <p>El clero constituiría el otro estamento privilegiado, dotado de sus propios fueros, exenciones fiscales y un considerable poder económico y cultural. En Cerezo, este grupo incluiría al párroco o párrocos de las iglesias locales (como la <a href='capitulo3/capitulo3.php#estructuras'>Iglesia de San Nicolás, cuya antigüedad ya hemos comentado</a>, y otras que pudieran existir), quizás algún capellán al servicio de familias nobles o cofradías, y los religiosos de los conventos o monasterios que pudieran estar establecidos en la villa o su comarca. Su papel no se limitaría estrictamente a lo espiritual; abarcaría también funciones culturales (como la escasa enseñanza existente o la llevanza de archivos parroquiales) y económicas, como diligentes administradores de importantes propiedades rústicas y urbanas, donadas o legadas a la Iglesia a lo largo de los siglos.</p>
        <p>La inmensa mayoría de la población pertenecería al estado llano, los pecheros, sobre quienes recaía la carga principal de la fiscalidad real, señorial y eclesiástica. Dentro de este amplio y heterogéneo grupo, existirían notables diferencias económicas y sociales: desde labradores acomodados, propietarios de sus propias tierras y ganado, hasta humildes jornaleros sin tierra que dependían del trabajo estacional para su sustento, pasando por una variada gama de artesanos (herreros, carpinteros, sastres, zapateros, etc.) y pequeños comerciantes que abastecían las necesidades básicas de la población. La movilidad social entre estamentos era prácticamente inexistente, y la pertenencia a uno u otro marcaba de forma determinante las oportunidades vitales, las obligaciones y los derechos de cada individuo desde su nacimiento.</p>
    </section>

    <section id="vida-religiosa-cultural">
        <h2>Vida Religiosa y Cultural: Devoción, Cofradías y Fiestas</h2>
        <p>La vida en Cerezo durante la Edad Moderna, al igual que en el resto de la Monarquía Hispánica, estaría profundamente marcada e imbuida por la religión católica, especialmente tras la clausura del Concilio de Trento (1545-1563) y el vigoroso impulso de la Contrarreforma. La parroquia o parroquias de la villa se erigirían como el epicentro indiscutible de la vida comunitaria, no solo para la celebración del culto dominical y festivo, sino también para la administración de los sacramentos (bautismo, matrimonio, extremaunción), el registro de los principales hitos vitales de los feligreses en los libros parroquiales, y la articulación de una parte importante de la sociabilidad a través de las numerosas cofradías y hermandades.</p>
        <p>Las cofradías, asociaciones de fieles dedicadas a la veneración de un santo patrón particular, a la Virgen María en alguna de sus múltiples advocaciones (del Rosario, del Carmen, etc.) o a algún misterio específico de la fe cristiana, desempeñarían un papel fundamental en la vida religiosa y social de Cerezo. Organizarían con gran pompa las fiestas religiosas de sus titulares, suntuosas procesiones, actos de caridad para con sus miembros más necesitados y la asistencia espiritual y material en el momento de la muerte. La devoción a santos locales o protectores de gran arraigo popular, como podrían ser <a href='capitulo8.php#santos-protectores-milagros'>San Vitores, cuyas leyendas y milagros ya evocamos</a>, o San Formerio, se mantendría viva y pujante, y las ermitas y santuarios diseminados por la comarca seguirían siendo importantes centros de peregrinación y devoción local o comarcal.</p>
        <p>En el ámbito cultural, la enseñanza formal estaría mayoritariamente en manos de la Iglesia, a través de modestas escuelas parroquiales o de alguna preceptoría de gramática donde se impartiría una formación básica centrada en la lectura, la escritura, las cuatro reglas aritméticas y, sobre todo, la doctrina cristiana. La cultura popular, eminentemente oral y tradicional, seguiría muy viva a través de la transmisión intergeneracional de romances, cantares, cuentos, refranes y antiguas tradiciones. Las fiestas, tanto las de carácter estrictamente religioso como aquellas de origen más profano o pagano (como los carnavales o las celebraciones solsticiales cristianizadas), con sus músicas interpretadas con instrumentos tradicionales, sus danzas y sus rituales específicos, constituirían los principales momentos de esparcimiento, sociabilidad y cohesión para la comunidad cerezana.</p>
    </section>

    <section id="crisis-conflictos-moderna">
        <h2>Cerezo ante las Crisis y Conflictos de la Edad Moderna</h2>
        <p>Contrariamente a una imagen idealizada de estabilidad, la Edad Moderna no fue un periodo de paz ininterrumpida para Castilla ni para sus villas. España, como potencia hegemónica durante el siglo XVI y parte del XVII, se vio envuelta en numerosas y costosas guerras europeas, especialmente bajo la dinastía de los Austrias (conflictos en Italia, las largas y sangrientas guerras en Flandes, los enfrentamientos con Francia o la lucha contra el Imperio Otomano en el Mediterráneo). Aunque es improbable que Cerezo fuera escenario directo de estas grandes contiendas internacionales, sus habitantes sufrirían inevitablemente sus consecuencias indirectas: las periódicas levas de jóvenes para engrosar los ejércitos reales, el constante aumento de los impuestos para financiar las campañas militares y las recurrentes crisis económicas y de subsistencia derivadas de los prolongados esfuerzos bélicos.</p>
        <p>El siglo XVII, en particular, es conocido como un periodo de crisis general que afectó a gran parte de Europa y con especial virulencia a la Monarquía Hispánica. Esta crisis se manifestó en un perceptible descenso demográfico (agravado por epidemias de peste, como la que asoló Castilla a principios de siglo), serias dificultades en la agricultura, contracción del comercio y frecuentes alteraciones monetarias. Es seguro que Cerezo de Río Tirón no fue ajena a estas dinámicas, experimentando la pérdida de población, el posible abandono de tierras marginales y el empobrecimiento de una parte considerable de sus habitantes. Ya en el siglo XVIII, la Guerra de Sucesión Española (1701-1714), que enfrentó a los partidarios de Felipe de Anjou (futuro Felipe V) con los del Archiduque Carlos de Austria, pudo implicar el paso de tropas, requisas forzosas o la exigencia de lealtades y recursos a villas castellanas como Cerezo, alterando temporalmente su vida cotidiana.</p>
        <p>Además de estos grandes conflictos de alcance general, la vida local no estaría exenta de sus propias tensiones y litigios. Los pleitos por la posesión de tierras o por derechos de pasto entre vecinos o con las aldeas del alfoz, las disputas jurisdiccionales entre el concejo y el posible señor de la villa (si lo hubo en algún momento) o con las autoridades eclesiásticas, o incluso episodios de bandolerismo en los caminos menos transitados, formarían parte de la realidad de la época. La capacidad de la comunidad cerezana para afrontar y superar estas crisis recurrentes, tanto las generales como las locales, sería fundamental para su pervivencia y su transmisión a las generaciones futuras.</p>
    </section>

    <section id="conclusion-ocaso-antiguo-regimen">
        <h2>Conclusión: Cerezo en el Ocaso del Antiguo Régimen</h2>
        <p>Al finalizar el siglo XVIII, Cerezo de Río Tirón se encontraba, como tantas otras villas y ciudades de España, en el ocaso del Antiguo Régimen, un complejo sistema social, económico y político que había definido su existencia durante tres largos siglos, pero que para entonces mostraba ya claros e inequívocos signos de agotamiento y crisis. La villa habría experimentado, a lo largo de esta extensa etapa, periodos de relativa prosperidad y crecimiento, alternados con momentos de profunda crisis demográfica y económica, pero manteniendo en esencia sus estructuras tradicionales: una economía predominantemente agraria y de subsistencia, una sociedad rígidamente estamental y un gobierno local que, aunque cada vez más sometido a la autoridad de la Corona, aún conservaba ciertas particularidades y ámbitos de actuación propios.</p>
        <p>Las nuevas ideas de la Ilustración, que comenzaban a circular con fuerza entre las élites cultas del país promoviendo la razón, la ciencia y la reforma, junto con los vientos revolucionarios que soplaban desde Francia desde 1789, pronto traerían consigo cambios drásticos y sin precedentes que transformarían radicalmente España y, con ella, a villas como Cerezo. El siglo XIX se abriría con la traumática experiencia de la Guerra de la Independencia contra Napoleón y el complejo y conflictivo inicio de la construcción del Estado liberal en España, procesos que marcarían el fin definitivo del Antiguo Régimen y el comienzo de una nueva y agitada etapa en la larga y rica historia de este singular enclave castellano. El legado de la Edad Moderna, con sus profundas inercias pero también con sus tímidas y a menudo contradictorias transformaciones, sería el inmediato punto de partida para que Cerezo afrontara los desafíos de <a href="capitulo11.php">una nueva etapa de su larga y rica historia</a>.</p>
    </section>

    <p><a href="capitulo9.php">Volver al Capítulo 9</a></p>
    <p><a href="index.php">Volver al Índice Principal</a></p>

    <?php require_once __DIR__ . '/../_footer.php'; ?>
    <script src="/js/layout.js"></script>
</body>
</html>
