<?php
return [
    ['label' => 'Inicio', 'url' => '/index.php'],
    ['label' => 'Nuestra Historia', 'url' => '/historia/historia.php'],
    ['label' => 'Historia de Cerezo', 'url' => '/historia_cerezo/index.php'],
    ['label' => 'Obispado de Auca', 'url' => '/historia/subpaginas/obispado_auca_cerezo.php'],
    ['label' => 'El Alfoz', 'url' => '/alfoz/alfoz.php'],
    ['label' => 'Lugares Emblemáticos', 'url' => '/lugares/lugares.php'],
    ['label' => 'Ruinas y Vestigios', 'url' => '/ruinas/index.php'],
    ['label' => 'Camino de Santiago', 'url' => '/camino_santiago/camino_santiago.php'],
    ['label' => 'Museo Colaborativo', 'url' => '/museo/galeria.php'],
    ['label' => 'Museo 3D', 'url' => '/museo/museo_3d.php'],
    ['label' => 'Subir Pieza', 'url' => '/museo/subir_pieza.php'],
    ['label' => 'Galería Colaborativa', 'url' => '/galeria/galeria_colaborativa.php'],
    ['label' => 'Tienda', 'url' => '/tienda/index.php'],
    ['label' => 'Planifica Tu Visita', 'url' => '/visitas/visitas.php'],
    ['label' => 'Programa de Citas', 'url' => '/citas/agenda.php'],
    ['label' => 'Cultura y Legado', 'url' => '/cultura/cultura.php'],
    ['label' => 'Personajes', 'url' => '/personajes/indice_personajes.html'],
    ['label' => 'Gestión de Yacimientos', 'url' => '/empresa/index.php'],
    ['label' => 'Foro', 'url' => '/foro/index.php'],
    ['label' => 'Blog', 'url' => '/blog.php'],
    ['label' => 'Contacto', 'url' => '/contacto/contacto.php'],
    ['label' => 'Influencia Romana', 'url' => '/historia/influencia_romana.php'],
];
