<?php
return [
    ['label' => 'menu_inicio', 'url' => 'index.php'],
    ['label' => 'menu_historia', 'url' => 'historia/historia.php'],
    ['label' => 'menu_historia_ampliada', 'url' => 'historia/historia_ampliada.php'],
    ['label' => 'menu_historia_cerezo', 'url' => 'historia_cerezo/index.php'],
    ['label' => 'menu_obispado_auca', 'url' => 'historia/subpaginas/obispado_auca_cerezo.php'],
    ['label' => 'menu_influencia_romana', 'url' => 'historia/influencia_romana.php'],
    ['label' => 'menu_alfoz', 'url' => 'alfoz/alfoz.php'],
    ['label' => 'menu_lugares', 'url' => 'lugares/lugares.php'],
    ['label' => 'menu_mapa_interactivo', 'url' => 'lugares/mapa_interactivo.php'],
    ['label' => 'menu_ruinas', 'url' => 'ruinas/index.php'],
    ['label' => 'menu_camino_santiago', 'url' => 'camino_santiago/camino_santiago.php'],
    ['label' => 'menu_museo_colaborativo', 'url' => 'museo/galeria.php'],
    ['label' => 'menu_museo_3d', 'url' => 'museo/museo_3d.php'],
    ['label' => 'menu_subir_pieza', 'url' => 'museo/subir_pieza.php'],
    ['label' => 'menu_galeria_colaborativa', 'url' => 'galeria/galeria_colaborativa.php'],
    ['label' => 'menu_tienda', 'url' => 'tienda/index.php'],
    ['label' => 'menu_planifica_visita', 'url' => 'visitas/visitas.php'],
    ['label' => 'menu_programa_citas', 'url' => 'citas/agenda.php'],
    ['label' => 'menu_cultura_legado', 'url' => 'cultura/cultura.php'],
    ['label' => 'menu_personajes', 'url' => 'personajes/indice_personajes.html'],
    ['label' => 'menu_gestion_yacimientos', 'url' => 'empresa/index.php'],
    ['label' => 'menu_foro', 'url' => 'foro/index.php'],
    ['label' => 'menu_blog', 'url' => 'blog.php'],
    ['label' => 'menu_documentacion', 'url' => 'docs/index.php'],
    ['label' => 'menu_contacto', 'url' => 'contacto/contacto.php'],
];
