name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Verificar atributos alt
        run: ./scripts/check_alt_texts.sh

      - name: Run PHPStan
        run: vendor/bin/phpstan

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover build/coverage.xml

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm ci

      - name: Run Puppeteer tests
        run: npm run test:puppeteer

      - name: Upload coverage artifact
        if: success() && always()
        uses: actions/upload-artifact@v3
        with:
          name: php-coverage
          path: build/coverage.xml
