name: Daily Agent

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  daily-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run daily agent
        run: |
          python scripts/daily_agent.py
