name: Test Suites

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: ./scripts/setup_environment.sh
      - name: Install test dependencies
        run: ./scripts/install_dev_deps.sh

      - name: Run PHPUnit
        run: vendor/bin/phpunit

      - name: Run Python tests
        run: python -m unittest tests/test_flask_api.py tests/test_graph_db_interface.py

      - name: Run Node tests
        run: npm test
